### ISSUE TITLE
Why use unitless line heights?

### ISSUE THREAD

**Issue by nicoqh** [inuitcss/tools.mixins#7]
Inuit calculates unitless line heights in order to place elements on a baseline.

Unitless line heights are usually advocated so that children don't inherit a calculated value from their parent. By using a unitless value (e.g. 1.5), a child will have a line height that is relative to its own font size and is therefore potentially different from its parent.

However, this is exactly what Inuit tries to avoid by calculating unitless line heights for every possible font size, all resulting in e.g. 1.5rem or a multiple thereof.

Why doesn't the `inuit-font-size()` mixin simply return (multiples of) `$inuit-base-line-height` in rems? Children would then inherit the correct calculated value and keep the vertical rhythm. Or have I missed something?

**Comment by csshugs** [comment]
@dnixx 

I guess [this](https://css-tricks.com/almanac/properties/l/line-height/#article-header-id-0) is a good answer to your question.

Apart from that, since this repository is now officially deprecated, I close this.
If your question is not answered or you want to discuss this issue further, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks.
